name: Deploy to demo (azure storage)

on:
  push:
    branches:
      - demo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - uses: actions/checkout@v2
        with:
          ref: demo
      - name: npm install, build
        run: |
          npm install
          npm run build:demo:prod

      # Azure CLI Upload to storage
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}
      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az storage blob upload-batch -d '$web' -s dist --account-name ngxadmin  --debug

      # Azure logout
      - name: logout
        run: |
          az logout
        if: always()
